AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple CRUD webservice.
Resources:
  AwsBilling:
    Type: AWS::Serverless::Function
    Properties:
      Handler: wether
      Runtime: go1.x
      Policies: [AmazonSSMFullAccess]
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /wether
            Method: GET
